
// ---------- Mock data ----------
export const STREETS = ["Nguyễn Văn Trỗi", "Phạm Văn Đồng", "Lê Lợi"];
export const GROUPS = {
  "Đào Thị Phấn": ["Tạp hóa A", "Tổ 1", "Gần tiệm sửa xe B"],
  "Cây Dầu": ["Tổ 3", "Khu chợ đêm"],
  "Lý Thái Tổ": ["Gần trường tiểu học"],
};
export const PERSONALITIES = [
  "Dễ tính",
  "Khó tính",
  "Không chỉ đường",
  "Chuyển khoản nhanh",
  "Chuyển khoản lâu",
];
export const ROOF_COLORS = [
  { name: "Đỏ", hex: "#c0392b" },
  { name: "Xanh dương", hex: "#2980b9" },
  { name: "Vàng", hex: "#e1a721" },
  { name: "Xám", hex: "#7f8c8d" },
];
export const GATE_COLORS = [
  { name: "Đen", hex: "#2c2c2a" },
  { name: "Nâu", hex: "#8b5e34" },
  { name: "Trắng", hex: "#d8d8d0" },
  { name: "Xanh lá", hex: "#3b6d11" },
];

export const INITIAL_CUSTOMERS = [
  {
    id: 1,
    name: "Chị Lan",
    phone: "0901234567",
    street: "Nguyễn Văn Trỗi",
    group: "Tạp hóa A",
    locationType: "house",
    roofColor: "Vàng",
    gateColor: "Đen",
    houseSide: "right",
    personality: "Dễ tính",
    description: "Nhà có chó nhỏ, không cắn. Để hàng trước cổng nếu không ai ở nhà.",
    timeNote: "Tránh 12h-13h trưa",
    lat: 10.9447,
    lng: 106.8243,
    addressUpdatedAt: "3 ngày trước",
  },
  {
    id: 2,
    name: "Anh Tuấn",
    phone: "0912345678",
    street: "Nguyễn Văn Trỗi",
    group: "Tổ 1",
    locationType: "boarding",
    boardingName: "Trọ Bình An",
    roomNumber: "P.203",
    floor: "2",
    roofColor: null,
    gateColor: "Trắng",
    houseSide: "left",
    personality: "Không chỉ đường",
    description: "Vào hẻm nhỏ, gửi xe ở đầu hẻm rồi đi bộ vào.",
    timeNote: "Sau 18h mới có nhà",
    lat: 10.9455,
    lng: 106.8251,
    addressUpdatedAt: "1 tuần trước",
  },
  {
    id: 3,
    name: "Cty Vietcombank CN3",
    phone: "0283812345",
    street: "Phạm Văn Đồng",
    group: "Tổ 3",
    locationType: "office",
    officeName: "Vietcombank chi nhánh 3",
    floor: "1",
    roofColor: null,
    gateColor: null,
    houseSide: "right",
    personality: "Dễ tính",
    description: "Gửi bảo vệ ở sảnh, có thể ký nhận thay.",
    timeNote: "",
    lat: 10.9502,
    lng: 106.8299,
    addressUpdatedAt: "Hôm nay",
  },
  {
    id: 4,
    name: "Cô Hạnh",
    phone: "0987654321",
    street: "Lê Lợi",
    group: "Gần trường tiểu học",
    locationType: "house",
    roofColor: "Đỏ",
    gateColor: "Xanh lá",
    houseSide: "left",
    personality: "Khó tính",
    description: "Gọi trước 5 phút. Không để hàng ngoài cổng.",
    timeNote: "",
    lat: 10.9411,
    lng: 106.8199,
    addressUpdatedAt: "2 tuần trước",
  },
];
